apiVersion: apps/v1
kind: Deployment
metadata:
  name: apprentice-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apprentice-app
  template:
    metadata:
      labels:
        app: apprentice-app
    spec:
      containers:
        - name: apprentice-app
          # This will be overridden by kustomization
          image: ghcr.io/easy-octo/apprentice-hire-exercise:v1.1.1
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
