# Great examples if you need other things can be found
# https://github.com/chainguard-dev/.github/tree/main/.github/chainguard
issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:easy-octo/apprentice-hire-exercise-manifests:ref:refs/heads/master
claim_pattern:
  workflow_ref: easy-octo/apprentice-hire-exercise-manifests/.github/workflows/release-please.yaml@refs/heads/master

permissions:
  contents: write
  pull_requests: write
