name: release-please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
        id: octo-sts
        with:
          scope: ${{ github.repository }} # Where to look for the trust policy <org>/<repo> (octo-sts must be installed on this repo)
          identity: release-please # prefix of the trust policy expected to be at <scope>/.github/chainguard/<identity>.sts.yaml

      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ steps.octo-sts.outputs.token }}
          release-type: simple
